import type {Metadata} from "next";
import "./reset.css";
import "./globals.css";
import {PrismicPreview} from '@prismicio/next'
import {repositoryName} from '@/prismicio'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        {children}
        <PrismicPreview repositoryName={repositoryName}/></body>
        </html>
    );
}
