// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  app_window_screenshot: dynamic(() => import("./AppWindowScreenshot")),
  embed: dynamic(() => import("./GistEmbed")),
  feature_blocks: dynamic(() => import("./FeatureBlocks")),
  project_image: dynamic(() => import("./ProjectImage")),
  text_block: dynamic(() => import("./TextBlock")),
};
