// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  app_icon: dynamic(() => import('./AppIcon')),
  app_window_screenshot: dynamic(() => import('./AppWindowScreenshot')),
  feature_blocks: dynamic(() => import('./FeatureBlocks')),
  navigation_item: dynamic(() => import('./NavigationItem')),
  project_image: dynamic(() => import('./ProjectImage')),
  text_block: dynamic(() => import('./TextBlock')),
};
